### PR TITLE
feat: update openapi on commit

### PR DESCRIPTION
**Pull request by artursudnik**
This PR implements automation that updates openapi.json documents.

To enable `pre-commit` git hook, execute `rush install` after pulling this change.

### CODE REVIEW

**Review by jrhender — APPROVED** [review]
This looks ok to me. IMO, the few seconds for a commit is fine and something we can improve.

**Comment by artursudnik** [comment]
I've found that the delay is probably caused by the TypeORM creating the DB schema on every start. I am not sure how to improve that.

**Comment by jrhender** [comment]
@artursudnik is there more work needed on this PR or can we mark as "Ready for review"?

**Comment by artursudnik** [comment]
Oh. I forgot to change the status. What could be done more is to reduce the execution time for the `vc-api`. But, it can be done as a separate PR if we figure out why it is so slow.

**Review by jrhender — APPROVED** [review]
Looks good, let's merge 👍

**Pull request merged**
